### ISSUE TITLE
onlyoffice basic docker setup not working

### ISSUE THREAD

**Issue by RikudouGoku** [gtsteffaniak/filebrowser#1496]
Following this:
https://filebrowserquantum.com/en/docs/user-guides/office-integration/basic-docker-setup/

Compose:
```
services:
  filebrowser:
    image: gtstef/filebrowser:latest
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      FILEBROWSER_ADMIN_PASSWORD: "change-me"
      TZ: "Europe/Stockholm"
      FILEBROWSER_ONLYOFFICE_SECRET: your_secret_here
    volumes:
      - /mnt/user:/folder
      - /mnt/user/appdata/filebrowser/data:/home/filebrowser/data
      - /mnt/user/appdata/filebrowser/tmp:/tmp/filebrowser
      - /mnt/user/appdata/filebrowser/database/database.db:/home/filebrowser/database.db

    ports:
      - 8000:80
    restart: unless-stopped
    networks:
      - filebrowser-network 
    deploy:
      resources:
        limits:
          memory: 4g     

  onlyoffice:
    image: onlyoffice/documentserver:latest
    ports:
      - "8001:80"
    environment:
      JWT_ENABLED: true
      JWT_SECRET: your_secret_here    
      JWT_HEADER: Authorization

    restart: unless-stopped
    networks:
      - filebrowser-network       

networks:
  filebrowser-network:
    name: filebrowser-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.32/28  
          gateway: 172.0.0.33
```

Config.yaml:
```
server:
  port: 80
  cacheDir: /tmp/filebrowser
  sources:
    - path: /folder
      config:
        defaultEnabled: true
auth:
  adminUsername: admin

integrations:
  office:
    url: "http://localhost"
    secret: "your_secret_here"
    viewOnly: false
```

onlyoffice logs:
```
onlyoffice-1  | find: ‘/var/www/onlyoffice/Data/certs’: No such file or directory
onlyoffice-1  | Generating WOPI private key...Done
onlyoffice-1  | Generating WOPI public key...Done
onlyoffice-1  |  * Starting PostgreSQL 16 database server
onlyoffice-1  |    ...done.
onlyoffice-1  |  * Starting RabbitMQ Messaging Server rabbitmq-server
onlyoffice-1  |    ...done.
onlyoffice-1  | Connection to localhost (::1) 5432 port [tcp/postgresql] succeeded!
onlyoffice-1  | Connection to localhost (::1) 5672 port [tcp/amqp] succeeded!
onlyoffice-1  | Starting supervisor: supervisord.
onlyoffice-1  |  * Starting periodic command scheduler cron
onlyoffice-1  |    ...done.
onlyoffice-1  |  * Starting nginx nginx
onlyoffice-1  |    ...done.
onlyoffice-1  | Generating AllFonts.js, please wait...Done
onlyoffice-1  | Generating presentation themes, please wait...Done
onlyoffice-1  | Generating js caches, please wait...Done
onlyoffice-1  | ds:docservice: stopped
onlyoffice-1  | ds:docservice: started
onlyoffice-1  | ds:converter: stopped
onlyoffice-1  | ds:converter: started
onlyoffice-1  |  * Reloading nginx configuration nginx
onlyoffice-1  |    ...done.
onlyoffice-1  | Installing plugins, please wait...Done
onlyoffice-1  |  * Reloading nginx configuration nginx
onlyoffice-1  |    ...done.
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-1  | [2025-11-01T20:12:06.788] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1  | [2025-11-01T20:12:06.791] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1  | [2025-11-01T20:12:06.797] [WARN] [localhost] [docId] [userId] nodeJS - worker 877 started.
onlyoffice-1  | [2025-11-01T20:12:06.799] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1  | [2025-11-01T20:12:06.799] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1  | [2025-11-01T20:12:46.927] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1  | [2025-11-01T20:12:46.931] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1  | [2025-11-01T20:12:46.944] [WARN] [localhost] [docId] [userId] nodeJS - worker 1169 started.
onlyoffice-1  | [2025-11-01T20:12:46.949] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1  | [2025-11-01T20:12:46.952] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/converter/err.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-1  | [2025-11-01T20:12:07.299] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-1  | [2025-11-01T20:12:07.314] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1  | [2025-11-01T20:12:07.315] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1  | [2025-11-01T20:12:07.510] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 9.1.0. Build: 168
onlyoffice-1  | [2025-11-01T20:12:46.268] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-1  | [2025-11-01T20:12:46.277] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1  | [2025-11-01T20:12:46.278] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1  | [2025-11-01T20:12:46.409] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 9.1.0. Build: 168
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/docservice/err.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/metrics/out.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/metrics/err.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/adminpanel/out.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/adminpanel/err.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/nginx.error.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver-example/out.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver-example/err.log <==
```

filebrowser logs:
```
filebrowser-1  | 2025/11/01 21:11:52 [INFO] Using admin password from FILEBROWSER_ADMIN_PASSWORD environment variable
filebrowser-1  | 2025/11/01 21:11:52 [INFO] Using OnlyOffice secret from FILEBROWSER_ONLYOFFICE_SECRET environment variable
filebrowser-1  | 2025/11/01 21:11:52 [INFO ] Initializing FileBrowser Quantum (v1.0.0-beta)
filebrowser-1  | 2025/11/01 21:11:52 [INFO ] Using Config file        : data/config.yaml
filebrowser-1  | 2025/11/01 21:11:52 [INFO ] Auth Methods             : [password]
filebrowser-1  | 2025/11/01 21:11:52 Using existing database  : /home/filebrowser/data/database.db
filebrowser-1  | 2025/11/01 21:11:52 [INFO ] Sources                  : [folder: /folder]
filebrowser-1  | 2025/11/01 21:11:52 Resetting admin user to default username and password.
filebrowser-1  | 2025/11/01 21:11:52 [INFO ] Running at               : http://localhost/
filebrowser-1  | 2025/11/01 21:11:53 [INFO ] initializing index: [folder]
filebrowser-1  | 2025/11/01 21:11:57 GET     | 200 | [::1]:38994     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/01 21:11:59 GET     | 200 | 172.0.0.33:34266 | admin        | 0ms          | "/files/appdata/test.docx"
filebrowser-1  | 2025/11/01 21:11:59 GET     | 200 | 172.0.0.33:34252 | admin        | 1496ms       | "/api/events?sessionId=x09eTsvU"
filebrowser-1  | 2025/11/01 21:11:59 GET     | 200 | 172.0.0.33:34268 | admin        | 20ms         | "/api/events?sessionId=x09eTsvU"
filebrowser-1  | 2025/11/01 21:11:59 GET     | 200 | 172.0.0.33:34276 | admin        | 0ms          | "/public/api/users?id=self"
filebrowser-1  | 2025/11/01 21:11:59 GET     | 200 | 172.0.0.33:34306 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/01 21:11:59 GET     | 200 | 172.0.0.33:34290 | admin        | 2ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder"
filebrowser-1  | 2025/11/01 21:11:59 GET     | 200 | 172.0.0.33:34308 | admin        | 4ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder&content=true"
filebrowser-1  | 2025/11/01 21:11:59 GET     | 200 | 172.0.0.33:34312 | admin        | 5ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/01 21:11:59 GET     | 200 | 172.0.0.33:34332 | admin        | 2ms          | "/api/onlyoffice/config?path=%2Fappdata%2Ftest.docx&source=folder"
filebrowser-1  | 2025/11/01 21:11:59 GET     | 200 | 172.0.0.33:34324 | admin        | 6ms          | "/api/events?sessionId=2iDHggYT"
filebrowser-1  | 2025/11/01 21:12:13 GET     | 200 | 172.0.0.33:55254 | admin        | 0ms          | "/files/appdata"
filebrowser-1  | 2025/11/01 21:12:13 GET     | 200 | 172.0.0.33:55270 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/01 21:12:13 GET     | 200 | 172.0.0.33:55284 | admin        | 0ms          | "/public/api/users?id=self"
filebrowser-1  | 2025/11/01 21:12:13 GET     | 200 | 172.0.0.33:55304 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/01 21:12:13 GET     | 200 | 172.0.0.33:55294 | admin        | 2ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/01 21:12:19 GET     | 200 | 172.0.0.33:34816 | admin        | 2ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder"
filebrowser-1  | 2025/11/01 21:12:19 GET     | 200 | 172.0.0.33:34832 | admin        | 3ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder&content=true"
filebrowser-1  | 2025/11/01 21:12:19 GET     | 200 | 172.0.0.33:34846 | admin        | 4ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/01 21:12:19 GET     | 200 | 172.0.0.33:34858 | admin        | 2ms          | "/api/onlyoffice/config?path=%2Fappdata%2Ftest.docx&source=folder"
filebrowser-1  | 2025/11/01 21:12:19 GET     | 200 | 172.0.0.33:34872 | admin        | 6ms          | "/api/events?sessionId=SS8OuOss"
filebrowser-1  | 2025/11/01 21:12:27 GET     | 200 | [::1]:52832     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/01 21:12:57 GET     | 200 | [::1]:55824     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/01 21:13:13 GET     | 200 | 172.0.0.33:34344 | admin        | 73966ms      | "/api/events?sessionId=2iDHggYT"
filebrowser-1  | 2025/11/01 21:13:27 GET     | 200 | [::1]:59624     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/01 21:13:57 GET     | 200 | [::1]:51728     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/01 21:14:27 GET     | 200 | [::1]:50696     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/01 21:14:57 GET     | 200 | [::1]:40968     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/01 21:15:27 GET     | 200 | [::1]:36240     | N/A          | 0ms          | "/health"
```

When trying to open a .docx file, nothing shows up

<img width="1768" height="895" alt="Image" src="https://github.com/user-attachments/assets/be81a300-e679-42f7-92c8-f2c257fb6cd5" />

This is running on UNRAID using Komodo for the compose manager.

**Comment by helgehatt** [comment]
I experience the same issue on Ubuntu.

The onlyoffice logs show `TypeError: Invalid URL` when I try to open .docx or .xlsx files.

Why is the access token sent as a query parameter? Why not add it as an Authorization header?

**Comment by RikudouGoku** [comment]
> Why is the access token sent as a query parameter? Why not add it as an Authorization header?

You asking me? I honestly have no clue. Just a user and know nothing about how this all works.

**Comment by helgehatt** [comment]
No I'm asking the author. Could be that OnlyOffice stopped supporting authorization in URL. Worked for me earlier at least.

**Comment by RikudouGoku** [comment]
> No I'm asking the author. Could be that OnlyOffice stopped supporting authorization in URL. Worked for me earlier at least.

got it, I believe the author is @gtsteffaniak

**Comment by gtsteffaniak** [comment]
This particular simple docker guide is brand new, I'll test it out from scratch and make sure each step is accurate today

**Comment by gtsteffaniak** [comment]
Sorry for the delay getting around to this, I tested this out and updated the docs. It should work now!

The main issue was the internalUrls were not configured in the docker compose.

Check out the [updated docs](https://filebrowserquantum.com/en/docs/user-guides/office-integration/basic-docker-setup/)

Thanks again for opening this so I could actually walk through that to make sure it worked :)

**Comment by RikudouGoku** [comment]
> Sorry for the delay getting around to this, I tested this out and updated the docs. It should work now!
> 
> The main issue was the internalUrls were not configured in the docker compose.
> 
> Check out the [updated docs](https://filebrowserquantum.com/en/docs/user-guides/office-integration/basic-docker-setup/)
> 
> Thanks again for opening this so I could actually walk through that to make sure it worked :)

hmm i still have issues.

```
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-1   | [2025-11-03T20:12:46.273] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-1   | [2025-11-03T20:12:46.934] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-03T20:12:46.935] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | tail: /var/log/onlyoffice/documentserver/converter/out.log: file truncated
onlyoffice-1   | tail: /var/log/onlyoffice/documentserver/docservice/out.log: file truncated
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-1   | [2025-11-04T20:12:46.274] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-1   | [2025-11-04T20:12:46.936] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-04T20:12:46.937] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | tail: /var/log/onlyoffice/documentserver/converter/out.log: file truncated
onlyoffice-1   | tail: /var/log/onlyoffice/documentserver/docservice/out.log: file truncated
onlyoffice-1   | find: ‘/var/www/onlyoffice/Data/certs’: No such file or directory
onlyoffice-1   |  * Starting PostgreSQL 16 database server
onlyoffice-1   |    ...done.
onlyoffice-1   |  * Starting RabbitMQ Messaging Server rabbitmq-server
onlyoffice-1   |    ...done.
onlyoffice-1   | Connection to localhost (::1) 5432 port [tcp/postgresql] succeeded!
onlyoffice-1   | Connection to localhost (::1) 5672 port [tcp/amqp] succeeded!
onlyoffice-1   | Unlinking stale socket /var/run/supervisor.sock
onlyoffice-1   | Starting supervisor: supervisord.
onlyoffice-1   |  * Starting periodic command scheduler cron
onlyoffice-1   |    ...done.
onlyoffice-1   |  * Starting nginx nginx
onlyoffice-1   |    ...done.
onlyoffice-1   | Generating AllFonts.js, please wait...Done
onlyoffice-1   | Generating presentation themes, please wait...Done
onlyoffice-1   | Generating js caches, please wait...Done
onlyoffice-1   | ds:docservice: stopped
onlyoffice-1   | ds:docservice: started
onlyoffice-1   | ds:converter: stopped
onlyoffice-1   | ds:converter: started
onlyoffice-1   |  * Reloading nginx configuration nginx
onlyoffice-1   |    ...done.
onlyoffice-1   | Installing plugins, please wait...Done
onlyoffice-1   |  * Reloading nginx configuration nginx
onlyoffice-1   |    ...done.
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-1   | [2025-11-05T16:45:47.763] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-05T16:45:47.765] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | [2025-11-05T16:45:47.771] [WARN] [localhost] [docId] [userId] nodeJS - worker 864 started.
onlyoffice-1   | [2025-11-05T16:45:47.772] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-05T16:45:47.772] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | [2025-11-05T16:46:09.735] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-05T16:46:09.737] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | [2025-11-05T16:46:09.741] [WARN] [localhost] [docId] [userId] nodeJS - worker 1152 started.
onlyoffice-1   | [2025-11-05T16:46:09.742] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-05T16:46:09.742] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/converter/err.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-1   | [2025-11-05T16:45:48.268] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-1   | [2025-11-05T16:45:48.278] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | [2025-11-05T16:45:48.278] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | [2025-11-05T16:45:48.408] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 9.1.0. Build: 168
onlyoffice-1   | [2025-11-05T16:46:08.277] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-1   | [2025-11-05T16:46:08.283] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | [2025-11-05T16:46:08.283] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | [2025-11-05T16:46:08.397] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 9.1.0. Build: 168
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/docservice/err.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/metrics/out.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/metrics/err.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/adminpanel/out.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/adminpanel/err.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/nginx.error.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver-example/out.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver-example/err.log <==
onlyoffice-1   | tail: /var/log/onlyoffice/documentserver/converter/out.log: file truncated
onlyoffice-1   | tail: /var/log/onlyoffice/documentserver/docservice/out.log: file truncated
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-1   | [2025-11-06T16:46:08.281] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-1   | [2025-11-06T16:46:09.741] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-06T16:46:09.742] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | tail: /var/log/onlyoffice/documentserver/converter/out.log: file truncated
onlyoffice-1   | tail: /var/log/onlyoffice/documentserver/docservice/out.log: file truncated
```




config.yaml:
```
server:
  port: 80
  cacheDir: /tmp/filebrowser
  internalUrl: "http://filebrowser" # corrosponds to the filebrowser container name
  sources:
    - path: /folder
      config:
        defaultEnabled: true
auth:
  adminUsername: admin

integrations:
  office:
    url: "http://localhost"
    internalUrl: "http://onlyoffice" # corrosponds to the onlyoffice container name
    secret: "your_secret_here"
    viewOnly: false

userDefaults:
  preview:
    highQuality: true
    image: true
    video: true
    motionVideoPreview: true
    office: true
    popup: true
    folder: true
  permissions:
    api: false
    admin: false
    modify: false
    share: false
    realtime: false
    delete: false
    create: false
    download: true
  disableOnlyOfficeExt: ".md .txt .pdf"   # list of file extensions to disable onlyoffice editor for
```

compose:
```
services:
  filebrowser:
    image: gtstef/filebrowser:latest
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      FILEBROWSER_ADMIN_PASSWORD: "change-me"
      TZ: "Europe/Stockholm"
      FILEBROWSER_ONLYOFFICE_SECRET: your_secret_here
    volumes:
      - /mnt/user:/folder
      - /mnt/user/appdata/filebrowser/data:/home/filebrowser/data
      - /mnt/user/appdata/filebrowser/tmp:/tmp/filebrowser
      - /mnt/user/appdata/filebrowser/database/database.db:/home/filebrowser/database.db

    ports:
      - 8000:80
    restart: unless-stopped
    networks:
      - filebrowser-network 
    deploy:
      resources:
        limits:
          memory: 4g     

  onlyoffice:
    image: onlyoffice/documentserver:latest
    ports:
      - "8001:80"
    environment:
      JWT_ENABLED: true
      JWT_SECRET: your_secret_here    
      JWT_HEADER: Authorization

    restart: unless-stopped
    networks:
      - filebrowser-network       

networks:
  filebrowser-network:
    name: filebrowser-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.32/28  
          gateway: 172.0.0.33
```

**Comment by helgehatt** [comment]
@RikudouGoku I think you're missing port in your internal urls. Should probably be `internalUrl: "http://onlyoffice:80"`.

I do however have the same issue myself. I have been using internalUrl and my setup have been working previously.

**Comment by RikudouGoku** [comment]
> [@RikudouGoku](https://github.com/RikudouGoku) I think you're missing port in your internal urls. Should probably be `internalUrl: "http://onlyoffice:80"`.
> 
> I do however have the same issue myself. I have been using internalUrl and my setup have been working previously.
Still does not work and I now have this in config.yaml:
```
server:
  port: 80
  cacheDir: /tmp/filebrowser
  internalUrl: "http://filebrowser" # corrosponds to the filebrowser container name
  sources:
    - path: /folder
      config:
        defaultEnabled: true
auth:
  adminUsername: admin

integrations:
  office:
    url: "http://localhost"
    internalUrl: "http://onlyoffice:80" # corrosponds to the onlyoffice container name
    secret: "your_secret_here"
    viewOnly: false

userDefaults:
  preview:
    highQuality: true
    image: true
    video: true
    motionVideoPreview: true
    office: true
    popup: true
    folder: true
  permissions:
    api: false
    admin: false
    modify: false
    share: false
    realtime: false
    delete: false
    create: false
    download: true
  disableOnlyOfficeExt: ".md .txt .pdf"   # list of file extensions to disable onlyoffice editor for
```


Entire onlyoffice log:
```
onlyoffice-1  | find: ‘/var/www/onlyoffice/Data/certs’: No such file or directory
onlyoffice-1  | Generating WOPI private key...Done
onlyoffice-1  | Generating WOPI public key...Done
onlyoffice-1  |  * Starting PostgreSQL 16 database server
onlyoffice-1  |    ...done.
onlyoffice-1  |  * Starting RabbitMQ Messaging Server rabbitmq-server
onlyoffice-1  |    ...done.
onlyoffice-1  | Connection to localhost (::1) 5432 port [tcp/postgresql] succeeded!
onlyoffice-1  | Connection to localhost (::1) 5672 port [tcp/amqp] succeeded!
onlyoffice-1  | Starting supervisor: supervisord.
onlyoffice-1  |  * Starting periodic command scheduler cron
onlyoffice-1  |    ...done.
onlyoffice-1  |  * Starting nginx nginx
onlyoffice-1  |    ...done.
onlyoffice-1  | Generating AllFonts.js, please wait...Done
onlyoffice-1  | Generating presentation themes, please wait...Done
onlyoffice-1  | Generating js caches, please wait...Done
onlyoffice-1  | ds:docservice: stopped
onlyoffice-1  | ds:docservice: started
onlyoffice-1  | ds:converter: stopped
onlyoffice-1  | ds:converter: started
onlyoffice-1  |  * Reloading nginx configuration nginx
onlyoffice-1  |    ...done.
onlyoffice-1  | Installing plugins, please wait...Done
onlyoffice-1  |  * Reloading nginx configuration nginx
onlyoffice-1  |    ...done.
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-1  | [2025-11-07T20:25:07.072] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1  | [2025-11-07T20:25:07.076] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1  | [2025-11-07T20:25:07.083] [WARN] [localhost] [docId] [userId] nodeJS - worker 877 started.
onlyoffice-1  | [2025-11-07T20:25:07.084] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1  | [2025-11-07T20:25:07.085] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1  | [2025-11-07T20:25:44.985] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1  | [2025-11-07T20:25:44.989] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1  | [2025-11-07T20:25:45.000] [WARN] [localhost] [docId] [userId] nodeJS - worker 1169 started.
onlyoffice-1  | [2025-11-07T20:25:45.002] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1  | [2025-11-07T20:25:45.002] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/converter/err.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-1  | [2025-11-07T20:25:07.741] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-1  | [2025-11-07T20:25:07.752] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1  | [2025-11-07T20:25:07.752] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1  | [2025-11-07T20:25:07.926] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 9.1.0. Build: 168
onlyoffice-1  | [2025-11-07T20:25:43.045] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-1  | [2025-11-07T20:25:43.057] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1  | [2025-11-07T20:25:43.057] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1  | [2025-11-07T20:25:43.195] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 9.1.0. Build: 168
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/docservice/err.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/metrics/out.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/metrics/err.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/adminpanel/out.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/adminpanel/err.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver/nginx.error.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver-example/out.log <==
onlyoffice-1  | 
onlyoffice-1  | ==> /var/log/onlyoffice/documentserver-example/err.log <==
```


entire filebrowser log:
```
filebrowser-1  | 2025/11/07 21:24:54 [INFO] Using admin password from FILEBROWSER_ADMIN_PASSWORD environment variable
filebrowser-1  | 2025/11/07 21:24:54 [INFO] Using OnlyOffice secret from FILEBROWSER_ONLYOFFICE_SECRET environment variable
filebrowser-1  | 2025/11/07 21:24:55 [INFO ] Initializing FileBrowser Quantum (v1.0.0-stable)
filebrowser-1  | 2025/11/07 21:24:55 [INFO ] Using Config file        : data/config.yaml
filebrowser-1  | 2025/11/07 21:24:55 [INFO ] Auth Methods             : [password]
filebrowser-1  | 2025/11/07 21:24:55 Using existing database  : /home/filebrowser/data/database.db
filebrowser-1  | 2025/11/07 21:24:55 [INFO ] Sources                  : [folder: /folder]
filebrowser-1  | 2025/11/07 21:24:55 Resetting admin user to default username and password.
filebrowser-1  | 2025/11/07 21:24:55 [INFO ] Running at               : http://localhost/
filebrowser-1  | 2025/11/07 21:24:56 [INFO ] initializing index: [folder]
filebrowser-1  | 2025/11/07 21:24:59 GET     | 200 | [::1]:51570     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:25:00 GET     | 200 | 192.168.0.162:54744 | admin        | 0ms          | "/files/appdata"
filebrowser-1  | 2025/11/07 21:25:00 GET     | 200 | 192.168.0.162:54752 | admin        | 0ms          | "/public/api/users?id=self"
filebrowser-1  | 2025/11/07 21:25:01 GET     | 200 | 192.168.0.162:54752 | admin        | 6ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/07 21:25:01 GET     | 200 | 192.168.0.162:54752 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:25:06 GET     | 200 | 192.168.0.162:54752 | admin        | 2ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder"
filebrowser-1  | 2025/11/07 21:25:06 GET     | 200 | 192.168.0.162:54752 | admin        | 2ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder&content=true"
filebrowser-1  | 2025/11/07 21:25:06 GET     | 200 | 192.168.0.162:54768 | admin        | 4ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/07 21:25:06 GET     | 200 | 192.168.0.162:54752 | admin        | 4ms          | "/api/onlyoffice/config?path=%2Fappdata%2Ftest.docx&source=folder"
filebrowser-1  | 2025/11/07 21:25:06 GET     | 200 | 192.168.0.162:54768 | admin        | 17ms         | "/api/events?sessionId=CrlKlrKI"
filebrowser-1  | 2025/11/07 21:25:06 GET     | 200 | 192.168.0.162:54782 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:25:20 GET     | 200 | 192.168.0.162:54782 | admin        | 9ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/07 21:25:20 GET     | 200 | 192.168.0.162:54752 | admin        | 14236ms      | "/api/events?sessionId=CrlKlrKI"
filebrowser-1  | 2025/11/07 21:25:23 GET     | 200 | 192.168.0.162:54782 | admin        | 2ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder"
filebrowser-1  | 2025/11/07 21:25:23 GET     | 200 | 192.168.0.162:54782 | admin        | 7ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder&content=true"
filebrowser-1  | 2025/11/07 21:25:23 GET     | 200 | 192.168.0.162:33058 | admin        | 6ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/07 21:25:23 GET     | 200 | 192.168.0.162:54782 | admin        | 4ms          | "/api/onlyoffice/config?path=%2Fappdata%2Ftest.docx&source=folder"
filebrowser-1  | 2025/11/07 21:25:23 GET     | 200 | 192.168.0.162:33058 | admin        | 22ms         | "/api/events?sessionId=CrlKlrKI"
filebrowser-1  | 2025/11/07 21:25:23 GET     | 200 | 192.168.0.162:33074 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:25:29 GET     | 200 | [::1]:50982     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:25:41 GET     | 200 | 192.168.0.162:33074 | admin        | 0ms          | "/files/appdata/test.docx"
filebrowser-1  | 2025/11/07 21:25:41 GET     | 200 | 192.168.0.162:54782 | admin        | 18107ms      | "/api/events?sessionId=CrlKlrKI"
filebrowser-1  | 2025/11/07 21:25:42 GET     | 200 | 192.168.0.162:59958 | admin        | 0ms          | "/public/api/users?id=self"
filebrowser-1  | 2025/11/07 21:25:42 GET     | 200 | 192.168.0.162:59958 | admin        | 2ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder"
filebrowser-1  | 2025/11/07 21:25:42 GET     | 200 | 192.168.0.162:59974 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:25:42 GET     | 200 | 192.168.0.162:59974 | admin        | 3ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder&content=true"
filebrowser-1  | 2025/11/07 21:25:42 GET     | 200 | 192.168.0.162:59958 | admin        | 4ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/07 21:25:42 GET     | 200 | 192.168.0.162:59974 | admin        | 2ms          | "/api/onlyoffice/config?path=%2Fappdata%2Ftest.docx&source=folder"
filebrowser-1  | 2025/11/07 21:25:42 GET     | 200 | 192.168.0.162:59958 | admin        | 18ms         | "/api/events?sessionId=gyHVqDsP"
filebrowser-1  | 2025/11/07 21:25:42 GET     | 200 | 192.168.0.162:59980 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:25:46 GET     | 200 | 192.168.0.162:59980 | admin        | 5ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/07 21:25:46 GET     | 200 | 192.168.0.162:59974 | admin        | 4306ms       | "/api/events?sessionId=gyHVqDsP"
filebrowser-1  | 2025/11/07 21:25:59 GET     | 200 | [::1]:35950     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:26:29 GET     | 200 | [::1]:41370     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:26:59 GET     | 200 | [::1]:46850     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:27:07 GET     | 200 | 192.168.0.162:59980 | admin        | 3ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder"
filebrowser-1  | 2025/11/07 21:27:07 GET     | 200 | 192.168.0.162:59980 | admin        | 2ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder&content=true"
filebrowser-1  | 2025/11/07 21:27:07 GET     | 200 | 192.168.0.162:36020 | admin        | 4ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/07 21:27:07 GET     | 200 | 192.168.0.162:59980 | admin        | 3ms          | "/api/events?sessionId=gyHVqDsP"
filebrowser-1  | 2025/11/07 21:27:07 GET     | 200 | 192.168.0.162:36020 | admin        | 3ms          | "/api/onlyoffice/config?path=%2Fappdata%2Ftest.docx&source=folder"
filebrowser-1  | 2025/11/07 21:27:07 GET     | 200 | 192.168.0.162:36024 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:27:29 GET     | 200 | [::1]:51016     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:27:49 GET     | 200 | 192.168.0.162:36024 | admin        | 0ms          | "/files/appdata/test.docx"
filebrowser-1  | 2025/11/07 21:27:49 GET     | 200 | 192.168.0.162:36020 | admin        | 41451ms      | "/api/events?sessionId=gyHVqDsP"
filebrowser-1  | 2025/11/07 21:27:49 GET     | 200 | 192.168.0.162:54794 | admin        | 0ms          | "/public/api/users?id=self"
filebrowser-1  | 2025/11/07 21:27:49 GET     | 200 | 192.168.0.162:54794 | admin        | 3ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder"
filebrowser-1  | 2025/11/07 21:27:49 GET     | 200 | 192.168.0.162:54794 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:27:49 GET     | 200 | 192.168.0.162:54808 | admin        | 3ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=folder&content=true"
filebrowser-1  | 2025/11/07 21:27:49 GET     | 200 | 192.168.0.162:54820 | admin        | 6ms          | "/api/resources?path=%252Fappdata&source=folder"
filebrowser-1  | 2025/11/07 21:27:49 GET     | 200 | 192.168.0.162:54820 | admin        | 2ms          | "/api/events?sessionId=InsLOnDE"
filebrowser-1  | 2025/11/07 21:27:49 GET     | 200 | 192.168.0.162:54808 | admin        | 2ms          | "/api/onlyoffice/config?path=%2Fappdata%2Ftest.docx&source=folder"
filebrowser-1  | 2025/11/07 21:27:49 GET     | 200 | 192.168.0.162:54794 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:27:59 GET     | 200 | [::1]:39554     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:28:29 GET     | 200 | [::1]:57368     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:29:00 GET     | 200 | [::1]:42240     | N/A          | 0ms          | "/health"
```

**Comment by helgehatt** [comment]
I was able to solve my issue by following the updated Docker guides and reverting my legacy config.

**Comment by RikudouGoku** [comment]
> I was able to solve my issue by following the updated Docker guides and reverting my legacy config.

Tried the same (deleted old folder and started over) now but still doesnt work.

compose:
```
services:
  filebrowser:
    image: gtstef/filebrowser:latest
    environment:
      TZ: "Europe/Stockholm"
    volumes:
      - /mnt/user:/srv
      - /mnt/user/appdata/filebrowser/data:/home/filebrowser/data
      - /mnt/user/appdata/filebrowser/tmp:/tmp/filebrowser
      - /mnt/user/appdata/filebrowser/data/config.yaml:/home/filebrowser/config.yaml
    ports:
      - 8000:80
    restart: unless-stopped
    networks:
      - filebrowser-network 
    deploy:
      resources:
        limits:
          memory: 4g     

  onlyoffice:
    image: onlyoffice/documentserver:latest
    ports:
      - "8001:80"
    environment:
      JWT_SECRET: your_secret_here    
    restart: unless-stopped
    networks:
      - filebrowser-network       

networks:
  filebrowser-network:
    name: filebrowser-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.32/28  
          gateway: 172.0.0.33
```
config.yaml:
```
server:
  port: 80
  database: data/database.db
  cacheDir: /tmp/filebrowser
  internalUrl: "http://filebrowser" # corrosponds to the filebrowser container name
  sources:
    - name: "files"
      path: "/srv" # corrosponds to the docker volume
      config:
        defaultEnabled: true
auth:
  adminPassword: yourpassword

integrations:
  office:
    url: "http://localhost"
    internalUrl: "http://onlyoffice:80" # corrosponds to the onlyoffice container name
    secret: "your_secret_here"
    viewOnly: false

userDefaults:
  preview:
    highQuality: true
    image: true
    video: true
    motionVideoPreview: true
    office: true
    popup: true
    folder: true
  permissions:
    api: false
    admin: false
    modify: false
    share: false
    realtime: false
    delete: false
    create: false
    download: true
  disableOnlyOfficeExt: ".md .txt .pdf"   # list of file extensions to disable onlyoffice editor for

```

<img width="406" height="111" alt="Image" src="https://github.com/user-attachments/assets/d3eb24ba-c722-44a5-ba81-e52e347cfcc9" />

<img width="642" height="345" alt="Image" src="https://github.com/user-attachments/assets/b991109d-88c3-4692-b749-027108c20ac8" />


```
filebrowser-1  | 2025/11/07 21:52:36 [WARN ] database file could not be found. If this is unexpected, the default path is `./database.db`, but it can be configured in the config file under `server.database`.
filebrowser-1  | 2025/11/07 21:52:37 [INFO ] Initializing FileBrowser Quantum (v1.0.0-stable)
filebrowser-1  | 2025/11/07 21:52:37 [INFO ] Using Config file        : config.yaml
filebrowser-1  | 2025/11/07 21:52:37 [INFO ] Auth Methods             : [password]
filebrowser-1  | 2025/11/07 21:52:37 Creating new database    : data/database.db
filebrowser-1  | 2025/11/07 21:52:37 [INFO ] Sources                  : [files: /srv]
filebrowser-1  | 2025/11/07 21:52:37 Resetting admin user to default username and password.
filebrowser-1  | 2025/11/07 21:52:37 [INFO ] Running at               : http://localhost/
filebrowser-1  | 2025/11/07 21:52:38 [INFO ] initializing index: [files]
filebrowser-1  | 2025/11/07 21:52:41 GET     | 200 | [::1]:39794     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:53:11 GET     | 200 | [::1]:33438     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:53:41 GET     | 200 | [::1]:35808     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:53:54 GET     | 200 | 192.168.0.162:58910 | N/A          | 0ms          | "/files/appdata"
filebrowser-1  | 2025/11/07 21:53:55 GET     | 401 | 192.168.0.162:58916 | N/A          | 0ms          | "/public/api/users?id=self"
filebrowser-1  | 2025/11/07 21:54:11 GET     | 200 | [::1]:35842     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:54:25 POST    | 200 | 192.168.0.162:58916 | N/A          | 80ms         | "/api/auth/login?username=admin&recaptcha="
filebrowser-1  | 2025/11/07 21:54:25 GET     | 200 | 192.168.0.162:58916 | admin        | 0ms          | "/public/api/users?id=self"
filebrowser-1  | 2025/11/07 21:54:25 GET     | 200 | 192.168.0.162:58916 | admin        | 5ms          | "/api/resources?path=%252Fappdata&source=files"
filebrowser-1  | 2025/11/07 21:54:25 GET     | 200 | 192.168.0.162:42732 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:54:29 PUT     | 200 | 192.168.0.162:42732 | admin        | 17ms         | "/api/users?id=1"
filebrowser-1  | 2025/11/07 21:54:41 GET     | 200 | [::1]:35162     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:54:42 GET     | 200 | 192.168.0.162:58916 | N/A          | 2ms          | "/static/img/placeholder.png"
filebrowser-1  | warning: dropping unclosed output
filebrowser-1  | 2025/11/07 21:54:42 GET     | 200 | 192.168.0.162:42732 | admin        | 100ms        | "/api/preview?path=%2Fappdata%2Ftest.docx&key=1762027280607&source=files&inline=true"
filebrowser-1  | 2025/11/07 21:54:43 GET     | 200 | 192.168.0.162:42732 | admin        | 5ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=files"
filebrowser-1  | 2025/11/07 21:54:43 GET     | 200 | 192.168.0.162:42732 | admin        | 6ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=files&content=true"
filebrowser-1  | 2025/11/07 21:54:43 GET     | 200 | 192.168.0.162:58916 | admin        | 7ms          | "/api/resources?path=%252Fappdata&source=files"
filebrowser-1  | 2025/11/07 21:54:43 GET     | 200 | 192.168.0.162:42732 | admin        | 3ms          | "/api/events?sessionId=oaD68Y7B"
onlyoffice-1   | find: ‘/var/www/onlyoffice/Data/certs’: No such file or directory
onlyoffice-1   | Generating WOPI private key...Done
onlyoffice-1   | Generating WOPI public key...Done
onlyoffice-1   |  * Starting PostgreSQL 16 database server
onlyoffice-1   |    ...done.
onlyoffice-1   |  * Starting RabbitMQ Messaging Server rabbitmq-server
onlyoffice-1   |    ...done.
onlyoffice-1   | Connection to localhost (::1) 5432 port [tcp/postgresql] succeeded!
onlyoffice-1   | Connection to localhost (::1) 5672 port [tcp/amqp] succeeded!
onlyoffice-1   | Starting supervisor: supervisord.
onlyoffice-1   |  * Starting periodic command scheduler cron
onlyoffice-1   |    ...done.
filebrowser-1  | 2025/11/07 21:54:43 GET     | 200 | 192.168.0.162:58916 | admin        | 5ms          | "/api/onlyoffice/config?path=%2Fappdata%2Ftest.docx&source=files"
onlyoffice-1   |  * Starting nginx nginx
onlyoffice-1   |    ...done.
onlyoffice-1   | Generating AllFonts.js, please wait...Done
onlyoffice-1   | Generating presentation themes, please wait...Done
filebrowser-1  | 2025/11/07 21:54:43 GET     | 200 | 192.168.0.162:34756 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:54:58 GET     | 200 | 192.168.0.162:34756 | admin        | 0ms          | "/files/appdata"
filebrowser-1  | 2025/11/07 21:54:58 GET     | 200 | 192.168.0.162:58562 | admin        | 0ms          | "/public/api/users?id=self"
filebrowser-1  | 2025/11/07 21:54:58 GET     | 200 | 192.168.0.162:58562 | admin        | 9ms          | "/api/resources?path=%252Fappdata&source=files"
filebrowser-1  | 2025/11/07 21:54:58 GET     | 200 | 192.168.0.162:58562 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:55:01 GET     | 200 | 192.168.0.162:58562 | admin        | 2ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=files"
filebrowser-1  | 2025/11/07 21:55:01 GET     | 200 | 192.168.0.162:58562 | admin        | 3ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=files&content=true"
filebrowser-1  | 2025/11/07 21:55:01 GET     | 200 | 192.168.0.162:50068 | admin        | 7ms          | "/api/resources?path=%252Fappdata&source=files"
filebrowser-1  | 2025/11/07 21:55:02 GET     | 200 | 192.168.0.162:58562 | admin        | 3ms          | "/api/onlyoffice/config?path=%2Fappdata%2Ftest.docx&source=files"
filebrowser-1  | 2025/11/07 21:55:02 GET     | 200 | 192.168.0.162:50068 | admin        | 4ms          | "/api/events?sessionId=I2YUVl61"
filebrowser-1  | 2025/11/07 21:55:02 GET     | 200 | 192.168.0.162:50072 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:55:03 GET     | 200 | 192.168.0.162:50072 | admin        | 0ms          | "/files/appdata"
filebrowser-1  | 2025/11/07 21:55:03 GET     | 200 | 192.168.0.162:50088 | admin        | 0ms          | "/public/api/users?id=self"
filebrowser-1  | 2025/11/07 21:55:03 GET     | 200 | 192.168.0.162:50088 | admin        | 7ms          | "/api/resources?path=%252Fappdata&source=files"
filebrowser-1  | 2025/11/07 21:55:03 GET     | 200 | 192.168.0.162:50088 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:55:11 GET     | 200 | [::1]:35734     | N/A          | 0ms          | "/health"
filebrowser-1  | 2025/11/07 21:55:32 GET     | 200 | 192.168.0.162:50088 | admin        | 7ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=files"
filebrowser-1  | 2025/11/07 21:55:32 GET     | 200 | 192.168.0.162:50088 | admin        | 6ms          | "/api/resources?path=%252Fappdata%252Ftest.docx&source=files&content=true"
filebrowser-1  | 2025/11/07 21:55:32 GET     | 200 | 192.168.0.162:50652 | admin        | 8ms          | "/api/resources?path=%252Fappdata&source=files"
filebrowser-1  | 2025/11/07 21:55:32 GET     | 200 | 192.168.0.162:50088 | admin        | 3ms          | "/api/onlyoffice/config?path=%2Fappdata%2Ftest.docx&source=files"
filebrowser-1  | 2025/11/07 21:55:32 GET     | 200 | 192.168.0.162:50652 | admin        | 8ms          | "/api/events?sessionId=6nrTDA40"
filebrowser-1  | 2025/11/07 21:55:32 GET     | 200 | 192.168.0.162:50660 | admin        | 0ms          | "/api/jobs/status/sources"
filebrowser-1  | 2025/11/07 21:55:41 GET     | 200 | [::1]:58170     | N/A          | 0ms          | "/health"
onlyoffice-1   | Generating js caches, please wait...Done
onlyoffice-1   | ds:docservice: stopped
onlyoffice-1   | ds:docservice: started
onlyoffice-1   | ds:converter: stopped
onlyoffice-1   | ds:converter: started
onlyoffice-1   |  * Reloading nginx configuration nginx
onlyoffice-1   |    ...done.
onlyoffice-1   | Installing plugins, please wait...Done
onlyoffice-1   |  * Reloading nginx configuration nginx
onlyoffice-1   |    ...done.
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-1   | [2025-11-07T20:52:49.490] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-07T20:52:49.492] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | [2025-11-07T20:52:49.499] [WARN] [localhost] [docId] [userId] nodeJS - worker 879 started.
onlyoffice-1   | [2025-11-07T20:52:49.500] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-07T20:52:49.500] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | [2025-11-07T20:53:29.136] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-07T20:53:29.140] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | [2025-11-07T20:53:29.150] [WARN] [localhost] [docId] [userId] nodeJS - worker 1171 started.
onlyoffice-1   | [2025-11-07T20:53:29.153] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 16; availableParallelism: 16
onlyoffice-1   | [2025-11-07T20:53:29.154] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/converter/err.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-1   | [2025-11-07T20:52:50.076] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-1   | [2025-11-07T20:52:50.083] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | [2025-11-07T20:52:50.084] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | [2025-11-07T20:52:50.256] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 9.1.0. Build: 168
onlyoffice-1   | [2025-11-07T20:53:28.488] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-1   | [2025-11-07T20:53:28.499] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | [2025-11-07T20:53:28.500] [WARN] [localhost] [docId] [userId] nodeJS - notifyLicenseExpiration(): expiration date is not defined
onlyoffice-1   | [2025-11-07T20:53:28.642] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 9.1.0. Build: 168
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/docservice/err.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/metrics/out.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/metrics/err.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/adminpanel/out.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/adminpanel/err.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver/nginx.error.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver-example/out.log <==
onlyoffice-1   | 
onlyoffice-1   | ==> /var/log/onlyoffice/documentserver-example/err.log <==
```

**Comment by Kurami32** [comment]
@RikudouGoku Assuming that you have your JWT secret the same in both (onlyoffice and filebrowser).

I think that you issue is in the url?

In your compose file you have it like this:
```yaml
  onlyoffice:
    image: onlyoffice/documentserver:latest
    ports:
      - "8001:80"    # You are using 8001 here as the external port
```

So I think that you forget to set the port in the url (the one that's reachable by the browser).

```yaml
integrations:
  office:
    url: "http://localhost:8001"   #  you should set it with the same port too
    internalUrl: "http://onlyoffice:80" # corrosponds to the onlyoffice container name
    secret: "your_secret_here"
    viewOnly: false
```

And instead of localhost I think that is better to use the IP of your machine/pc (unless you only access fbq and onlyoffice in that one machine/pc).

**Comment by RikudouGoku** [comment]
> [@RikudouGoku](https://github.com/RikudouGoku) Assuming that you have your JWT secret the same in both (onlyoffice and filebrowser).
> 
> I think that you issue is in the url?
> 
> In your compose file you have it like this:
> 
>   onlyoffice:
>     image: onlyoffice/documentserver:latest
>     ports:
>       - "8001:80"    # You are using 8001 here as the external port
> So I think that you forget to set the port in the url (the one that's reachable by the browser).
> 
> integrations:
>   office:
>     url: "http://localhost:8001"   #  you should set it with the same port too
>     internalUrl: "http://onlyoffice:80" # corrosponds to the onlyoffice container name
>     secret: "your_secret_here"
>     viewOnly: false
> And instead of localhost I think that is better to use the IP of your machine/pc (unless you only access fbq and onlyoffice in that one machine/pc).

IT WORKS! 

<img width="1907" height="611" alt="Image" src="https://github.com/user-attachments/assets/1baa0f20-0d28-41f3-bb92-3a5e2d0bc742" />

I changed the config.yaml (url part).

> server:
>   port: 80
>   database: data/database.db
>   cacheDir: /tmp/filebrowser
>   internalUrl: "http://filebrowser" # corrosponds to the filebrowser container name
>   sources:
>     - name: "files"
>       path: "/srv" # corrosponds to the docker volume
>       config:
>         defaultEnabled: true
> auth:
>   adminPassword: yourpassword
> 
> integrations:
>   office:
>     url: "http://localhost:8001"
>     internalUrl: "http://onlyoffice:80" # corrosponds to the onlyoffice container name
>     secret: "your_secret_here"
>     viewOnly: false
> 
> userDefaults:
>   preview:
>     highQuality: true
>     image: true
>     video: true
>     motionVideoPreview: true
>     office: true
>     popup: true
>     folder: true
>   permissions:
>     api: false
>     admin: false
>     modify: false
>     share: false
>     realtime: false
>     delete: false
>     create: false
>     download: true
>   disableOnlyOfficeExt: ".md .txt .pdf"   # list of file extensions to disable onlyoffice editor for


Tried with incognito after it did not work first but after it worked in incognito it works in regular Brave browser.


Now that this works and I do not want the default "your_secret_here" JWT, can I just change it in the compose JWT_SECRET env variable and in the config.yaml section? And what about  `adminPassword: yourpassword`?

**Comment by Kurami32** [comment]
Glad it worked! Yep, you can (and should) change that JWT secret, generate one with command from the [step 01](https://filebrowserquantum.com/en/docs/user-guides/office-integration/basic-docker-setup/#step-1-generate-jwt-secret) in the docs. Then paste the EXACT same output that the command gives you in both, the `config.yaml` and in the compose file too.

> And what about adminPassword: yourpassword?

That's your password for the default admin user, you should change it too with something more secure.

**Comment by RikudouGoku** [comment]
> Glad it worked! Yep, you can (and should) change that JWT secret, generate one with command from the [step 01](https://filebrowserquantum.com/en/docs/user-guides/office-integration/basic-docker-setup/#step-1-generate-jwt-secret) in the docs. Then paste the EXACT same output that the command gives you in both, the `config.yaml` and in the compose file too.
> 
> > And what about adminPassword: yourpassword?
> 
> That's your password for the default admin user, you should change it too with something more secure.

Thanks for the help!
