### ISSUE TITLE
Am I not able to use pre-existing folders?

### ISSUE THREAD

**Issue by LATINO-BICEPS** [gtsteffaniak/filebrowser#1497]
**Description**

I am unable to browse through pre-existing folders (files are OK) and instead get `500: path not accessible: file/folder does not exist in metadata:`. Folders created through the webui can be accessed as intended. I am using docker with the following folder structure.
```
data/
├── folder-pre-existing❌ (500: path not accessible: file/folder does not exist in metadata: /folder-pre-existing)
├── file-pre-existing ✅
├── folder-created-directly-in-webui ✅
└── file-created-directly-in-webui ✅
```
```yml
# docker-compose.yml
...
    image: gtstef/filebrowser:beta
    user: "1000:1000"
    environment:
      FILEBROWSER_CONFIG: /config/config.yaml
      FILEBROWSER_DATABASE: /config/database.db
      TZ: Asia/Hong_Kong
    volumes:
      # config
      - ./filebrowser-quantum/config:/config
      - ./tmp:/home/filebrowser/tmp
      # data volumes
      - ./data:/data
...
```
```yml
# config.yml
server:
  numImageProcessors: 3
  baseURL: "/"
  logging:
    - levels: "info|warning|error"
      output: ""
  # specify volume paths here
  sources:
    - path: "/data"
      name: "Root Directory"
      config:
        defaultUserScope: "/"
        defaultEnabled: true    
userDefaults:
  preview:
    disableHideSidebar: true
    highQuality: true
    image: true
    video: true
    motionVideoPreview: true
    office: true
    popup: true
    autoplayMedia: true
    defaultMediaPlayer: true
    folder: true
  permissions:
    download: true
  loginMethod: "password"
integrations:
  media:
    ffmpegPath: "ffmpeg"
```

Docker log when trying to access the folder:
```
filebrowser  | 2025/11/02 18:44:41 GET     | 500 | 192.168.169.203:49365 | admin        | 0ms          | "/api/resources?path=%252Fdata2%252F&source=Root%2520Directory"
```

All files and folders are owned by user 1000 `chown -R services: ./data`
```sh
drwxr-xr-x 6 services services 4.0K Nov  2 18:42 data
```

I have tried deleting the `database.db` and recreating the container but no dice. I'm a bit stumped. Is this intended behaviour?

**Comment by ghost** [comment]
Something similar happens to me; when I try to upload a folder, it gives an error.

<img width="897" height="590" alt="Image" src="https://github.com/user-attachments/assets/bc7e51fc-c640-439b-8aa0-2354756ffa1c" />

**Comment by ghost** [comment]
Running on Docker Ubuntu Server 20.4 with these files:
config
server:
  sources:
    - path: "./servidor"
      config:
        defaultEnabled: true
        createUserDir: true
        defaultUserScope: "/"
frontend:
  name: "Servidor"
auth:
  adminUsername: admin
  adminPassword: admin
  methods:
    password:
      enabled: true

docker-compose

`services:

  filebrowser-quantum:
    image: gtstef/filebrowser
    container_name: filebrowser-quantum
    restart: unless-stopped
    ports:
      - "8200:80"
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      TZ: "Europe/Madrid"
    volumes:
      - ./config.yaml:/home/filebrowser/data/config.yaml
      - ./data:/home/filebrowser/data
      - ./servidor:/home/filebrowser/servidor`

**Comment by Kurami32** [comment]
@LATINO-BICEPS I can replicate this, and is not only with your setup.

But for me is the contrary, I can upload folders (yup, folders) in my pre-existing directories, but I can't upload folders in directories created in the WebUI (but upload files work fine) - I got the same error as you.

So, yes, this seems to be a bug.

---

Also, this bug seems to be since time ago, just that nobody noticed it. I tried with older versions and the one without this bug is `v0.8.7`.

**Comment by LATINO-BICEPS** [comment]
> But for me is the contrary, I can upload folders (yup, folders) in my pre-existing directories, but I can't upload folders in directories created in the WebUI (but upload files work fine) - I got the same error as you.

Huh. I wonder what the differences are between our environments.  My `config.yml` has practically no changes from the default and I have only specified different locations for my config and database in my compose file. I suppose I also specified a user but that shouldn't be it..

**Comment by LATINO-BICEPS** [comment]
@elduque477 Is this a shared upload folder? If so, I ran into the same issue too. But is your problem limited to just the upload folders only?

**Comment by ghost** [comment]
I get this error when uploading any folder.
This doesn't happen with files.
It seems that when trying to upload a folder, it doesn't create it, so the files in that folder return an error.

**Comment by ghost** [comment]
Example: if I want to directly upload a folder called "Goodbye (2019)", which contains an mkv file and a jpg file, it throws this error.

<img width="408" height="93" alt="Image" src="https://github.com/user-attachments/assets/2bbb089f-94d7-470d-ad75-160ed0c603c7" />

**Comment by ghost** [comment]
One thing I miss is more information about file uploads.

In my opinion, we should see not only the upload percentage, but also the estimated completion time and the upload bitrate. I think this is vital information. Great project, and thanks for sharing.

**Comment by LATINO-BICEPS** [comment]
I do not know exactly how I fixed this issue as it was a combination of things I did. I have it now fully configured with Authentik and Caddy. No issues with permissions or the like. These are the differences between both times setting it up from what I can remember.

1. I pinned my image to `1.1.0-dev@sha256:de9b838da80ba85e0206eefdc935201408fce9f0221610417ea9f3764743f7f0` from `beta@sha256:2d94904ede9e612f4948110e06054b220c3990c7841f567711029d85eb1210db`. I do not know if there has been any code changes regarding file paths, if at all.
2. I ran it as root first and then changed my user to 1000:1000. I do not have any cache dir specified in my compose file. I only `chown -R 1000:  data_dir` anything the container needed.
3. My initial setup was `/config/{*.db,*.yaml}` but this time I kept it default

I may have missed some things but this is all I can remember after spending hours troubleshooting.

**Comment by Kurami32** [comment]
@LATINO-BICEPS I just want to ask, but you can upload folders to a folder that you have created in the WebUI?

**Comment by LATINO-BICEPS** [comment]
@Kurami32 I was always able to upload folders to folders created in the WebUI. My original issue was for uploading files/folders to folders that were not created in the WebUI, but already existing folders in the filesystem.

Edit: I actually forgot the original issue myself. To answer your question, yes all features work, I am able to do anything.

**Comment by Kurami32** [comment]
Is odd, because is not working for me (even in the `dev` version, which btw, be careful since is having lots of changes), and I think that is the same/similar for @elduque477 (?)

I think that I'll open a separate issue for this. Anyways, thanks for answer!

**Comment by ghost** [comment]
In the latest version, the same problem persists. If I create a folder called "example cinema" and try to upload a folder containing an MKV file and a JPG cover, it throws an error and fails to upload.

**Comment by Kurami32** [comment]
@elduque477 This happens when you try to upload to an empty directory? 
I was testing and if you create a file (or whatever thing), uploading a folder will work. I created a separate issue #1571

**Comment by ghost** [comment]
It works with individual files; the error occurs when uploading a folder with several files.
