### ISSUE TITLE
Downloadlink with password error: 401 - "could not authenticate share request"

### ISSUE THREAD

**Issue by Felix2M** [gtsteffaniak/filebrowser#1593]
**Description**
I tried copying a download link to the clipboard, but with password for authentication:

<img width="1642" height="371" alt="Image" src="https://github.com/user-attachments/assets/c80d7400-9a57-4502-9dca-5827ca49f5d2" />

**Expected behaviour**
Getting a Link where I can download the shared folder directly

**What is happening instead?**
It shows the following message in a new browser tab:

<img width="526" height="277" alt="Image" src="https://github.com/user-attachments/assets/6085f2f9-1246-4e64-ae46-106d8171f0a3" />

**Additional context**

**How to reproduce?**
Create a folder, try to share it, set a password and try to open with the direct downloadlink.

**Comment by gtsteffaniak** [comment]
Thanks for opening, this is a known issue fixed in dev build. Will be fixed in 1.1.0-beta and patched in 1.0.2-stable next week

**Comment by gtsteffaniak** [comment]
should be solved in v1.1.0-beta -- will close for now and patch within a week for stable as well

**Comment by gtsteffaniak** [comment]
I think I misunderstood the issue here, I don't think I solved this in beta 1.1.1. This is something that needs a UI and the direct download link should be disabled when a share password exists.

Having a direct download link would defeat the purpose of a share password to include the password in the link

**Comment by Felix2M** [comment]
@gtsteffaniak I thought the feature would work like a direct download link, but with a popup to enter the password. But if that's not possible it would be better to disable it, like you said.

Thanks for having a second look on this issue!

**Comment by gtsteffaniak** [comment]
It could work like that, the download link was meant to be an api reference, but in that scenario, it would link to the UI.

I think you're right it should work like that but needs a bit more work to make sure that works smoothly.

**Comment by VonAdam1** [comment]
I still have this, from regular links. It doesn't seem to affect anything but doesn't look good when sending share links to clients.
*I'm on the latest stable version

<img width="498" height="137" alt="Image" src="https://github.com/user-attachments/assets/23d2709a-6de7-47e7-bee2-99b484ed5327" />

**Comment by gtsteffaniak** [comment]
@VonAdam1 I think that's resolved on the latest versions. Which version are you running?

**Comment by VonAdam1** [comment]
@gtsteffaniak Yes!, seemed to be fixed I'm on v1.1.4-beta now.

**Comment by gtsteffaniak** [comment]
closing as fixed in [v1.1.5-beta](https://github.com/gtsteffaniak/filebrowser/releases/tag/v1.1.5-beta)

will reach stable sometime next week.
