### ISSUE TITLE
Some PHP files not opening

### ISSUE THREAD

**Issue by wilcochris** [gtsteffaniak/filebrowser#1726]
**Description**
When trying to open some PHP files in Filebrowser, it only gives the option to download or open the file in the browser

**Expected behaviour**
All PHP files to open in the built-in text editor

**What is happening instead?**
Some are only offering to download or open the file in an external browser (the external browser will only show the file and not the contents).

**Additional context**
One file in particular has flag emojis in it so I am unsure if this is causing the issue (though I expect not since it opens for a little while upon creation.

**How to reproduce?**
Create the attached file and see the results

**Files**

[countries-arrays.php](https://github.com/user-attachments/files/24145386/countries-arrays.php) - File cannot be opened

[aapt.dd.php](https://github.com/user-attachments/files/24145388/aapt.dd.php) - Example file that can be opened

<img width="1871" height="931" alt="Image" src="https://github.com/user-attachments/assets/475a74c0-0a68-42c0-b256-f815226385d5" /> - Screenshot showing a PHP file that can be opened.

<img width="1920" height="931" alt="Image" src="https://github.com/user-attachments/assets/c6ab63da-fcaa-4822-a64b-fdd3347ca070" /> - Screenshot showing the PHP file that cannot be opened

**Comment by wilcochris** [comment]
I will also add that there is nothing in the logs to show why this would happen

**Comment by gtsteffaniak** [comment]
what version are you running?

When I check on beta 1.1.4 I can open `countries-arrays.php` just fine.

in the past there was issues with emojis but that should be resolved in recent versions (latest stable too)

<img width="2730" height="1134" alt="Image" src="https://github.com/user-attachments/assets/2c15cad1-0d72-4e0d-a743-6aa92d79ded3" />

**Comment by wilcochris** [comment]
I'm currently on 1.0.3-stable

The weird thing is, I created a new file of the same name with the same content and it opens without issue.

It just seems to be the first couple of files I created that did that.

I still can't open them and they just say I can download it or open the file. When the PHP or TXT file opens in the browser it renders the file contents without issue.

**Comment by gtsteffaniak** [comment]
Yeah it's a bit difficult to say for sure since I can't replicate the issue.

The file you uploaded I tried and it works. If you download that copy from the web can you view it?

**Comment by wilcochris** [comment]
The file that won't open in the text editor I can view in the browser and it parses the content.

I can download it and view it in the browser parsed or open in N++ and view the contents.

All the file is, is an array of countries and their emoji flag.

**Comment by gtsteffaniak** [comment]
ah thanks. emojis might be triggering it as non-text format. Could you provide the file?

**Comment by wilcochris** [comment]
The countries-array.php file is the file in question.

I'm not sure it will be the emojis though as I created another file and this opens in FileBrowser for editing without any issue

**Comment by gtsteffaniak** [comment]
yeah the strange thing is I can open that file just fine. Does the same occur on v1.1.0 ?

**Comment by wilcochris** [comment]
I've just updated to v1.1.0 and the files now open as normal.

I have noticed another little nuance since updating to v1.1.0 - in some files, the cursor sits right on the character and it's often hard to tell which character it is focusing on. It's also hard to get a screenshot of the issue. I will try and do a screen recording showing it

**Comment by gtsteffaniak** [comment]
can you test v1.2.2 beta, I have made the rules for whats considered "text file" more lenient.
