### ISSUE TITLE
.SRT files with video files creates an Error 500

### ISSUE THREAD

**Issue by bonza-views** [gtsteffaniak/filebrowser#678]
**Description**
- If you have an .srt (subtitle) files in the same folder as .mp4 video files, a 500 Error pops on the screen when you go to play a video file. The video plays as expected.
- If you change the extension of the .srt file, the problem goes away.
- I haven't tried with other type video files, but I expect the result would be the same.
- It doesn't happen with non-video type files, so maybe the video player is responsible?

**Expected behaviour**
Everything works fine, except an Error 500 pops on screen.

**What is happening instead?**
2025/05/26 08:11:51 GET     | 200 | 192.168.2.10:55564 | admin        | 0ms          | "/api/resources?path=%2Ftest%2Fx.y.mp4&source=srv"
2025/05/26 08:11:51 GET     | 200 | 192.168.2.10:55564 | admin        | 0ms          | "/api/resources?path=%2Ftest%2Fx.y.mp4&source=srv&content=true"
2025/05/26 08:11:51 GET     | 500 | 192.168.2.10:55564 | admin        | 0ms          | "/api/resources?path=%2Ftest%2Fx.srt&source=srv&content=true"
2025/05/26 08:11:51 GET     | 206 | 192.168.2.10:55564 | admin        | 0ms          | "/api/raw?files=srv::%2Ftest%2Fx.y.mp4&inline=true"
2025/05/26 08:11:52 GET     | 206 | 192.168.2.10:55564 | admin        | 43ms         | "/api/raw?files=srv::%2Ftest%2Fx.y.mp4&inline=true"
2025/05/26 08:11:57 GET     | 200 | 192.168.2.10:55567 | admin        | 1ms          | "/api/resources?path=%2Ftest%2F&source=srv"

If you look at the log where the error 500 is, it's trying to access a file called "x.srt" but the file is called "x.y.srt".

**Additional context**
This is a low priority edge case.

**How to reproduce?**
- Create a test folder.
- Put any .mp4 file in there (not sure about other video file types), and rename it to "x.y.mp4". The name is not important, but it must have at least two dots. This is common for TV series files eg. "Reacher.S01E01.mp4"
- Create a file called "x.y.srt". The content is not important, but it must be a ".srt" file.
- When you double click the MP4 file an error 500 occurs.
- The "x" and "y" in the filename can be anything, you will get the same result. However if the filename has only one dot the problem is not present.

**Comment by gtsteffaniak** [comment]
Thanks for opening an issue! I will take a look

**Comment by bonza-views** [comment]
This is still erroring for me with 0.7.5-beta

**Comment by gtsteffaniak** [comment]
I fixed an issue with source path and it resolved it for me when debugging.

Can you send the logs you have on v0.7.5 for me to check?

**Comment by bonza-views** [comment]
It only errors if the filenames have TWO or more full-stops. One full-stop = no error.

"Error 500: could not stat path: /Dealers/Bob.the.Builder/srt/x.srt, lstat /Dealers/Bob.the.Builder/srt/x.srt: no such file or directory"

2025/05/29 21:42:12 GET     | 200 | 192.168.2.10:60443 | admin        | 1ms          | "/api/resources?path=%2Fsrt%2Fx.y.mp4&source=Bob.the.Builder"
2025/05/29 21:42:12 GET     | 200 | 192.168.2.10:60443 | admin        | 0ms          | "/api/resources?path=%2Fsrt%2Fx.y.mp4&source=Bob.the.Builder&content=true"
2025/05/29 21:42:12 GET     | 500 | 192.168.2.10:60443 | admin        | 0ms          | "/api/resources?path=%2Fsrt%2Fx.srt&source=Bob.the.Builder&content=true"
2025/05/29 21:42:12 GET     | 206 | 192.168.2.10:60444 | admin        | 69ms         | "/api/raw?files=Bob.the.Builder::%2Fsrt%2Fx.y.mp4&inline=true"
2025/05/29 21:42:12 GET     | 206 | 192.168.2.10:60443 | admin        | 4ms          | "/api/raw?files=Bob.the.Builder::%2Fsrt%2Fx.y.mp4&inline=true"
2025/05/29 21:42:12 GET     | 206 | 192.168.2.10:60442 | admin        | 5ms          | "/api/raw?files=Bob.the.Builder::%2Fsrt%2Fx.y.mp4&inline=true"
2025/05/29 21:42:12 GET     | 206 | 192.168.2.10:60442 | admin        | 38ms         | "/api/raw?files=Bob.the.Builder::%2Fsrt%2Fx.y.mp4&inline=true"
2025/05/29 21:42:22 GET     | 200 | 192.168.2.10:60445 |              | 64ms         | "/static/img/icons/favicon-256x256.png"

**Comment by gtsteffaniak** [comment]
Can you confirm if this is still happening on latest. What you are describing should be caused because you have only one source configured and the I fixed that issue.

New versions shouldn't have this issue, if you do is it still the same error?

**Comment by bonza-views** [comment]
Its still broken on v0.7.7-beta, same error.
I had two sources at one point and it still failed then.

I think the problem is line 27 of backend/indexing/iteminfo/utils.go. The Split on "." is resulting in an array, and you are only using the first element of the array. This works fine if the filename has only one full stop, but parts of the filename go missing if the filename has more that one full stop.

Maybe line 27 could be replaced with these two lines;
```
	reFullPathBase := regexp.MustCompile(`^(.*)\.[^.]*$`)  // Match all characters before the LAST full stop
	fullPathBase := reFullPathBase.FindStringSubmatch(i.Path)[1]
```
NOTE This code will error if the i.Path string has no full stop in it. I'm not sure if that is possible?

Current code:

		for _, subtitleExt := range []string{".vtt", ".srt", ".lrc", ".sbv", ".ass", ".ssa", ".sub", ".smi"} {
			if strings.HasSuffix(f.Name, subtitleExt) {
				fullPathBase := strings.Split(i.Path, ".")[0]
				i.Subtitles = append(i.Subtitles, fullPathBase+subtitleExt)
			}
		}

DEBUG LOG

2025/06/08 05:22:28 [INFO ] middleware.go:419: GET     | 200 | 192.168.2.10:61804 | "/api/resources?path=%2FMedia%2F&source=srv"
2025/06/08 05:22:29 [INFO ] middleware.go:419: GET     | 304 | 192.168.2.10:61805 | "/api/preview?path=%2FMedia%2Fname.S01E06.1080p.srt&key=1749359178914&source=srv&inline=true"
2025/06/08 05:22:29 [INFO ] middleware.go:419: GET     | 304 | 192.168.2.10:61804 | "/api/preview?path=%2FMedia%2Fname.S01E06.1080p.mp4&key=1749359178914&source=srv&inline=true"
2025/06/08 05:22:33 [INFO ] middleware.go:419: GET     | 200 | 192.168.2.10:61804 | "/api/resources?path=%2FMedia%2Fname.S01E06.1080p.mp4&source=srv"
2025/06/08 05:22:33 [DEBUG] files.go:80: skipping large text file contents (20MB limit): /Media/name.S01E06.1080p.mp4 name.S01E06.1080p.mp4
2025/06/08 05:22:33 [INFO ] middleware.go:419: GET     | 200 | 192.168.2.10:61804 | "/api/resources?path=%2FMedia%2Fname.S01E06.1080p.mp4&source=srv&content=true"
2025/06/08 05:22:33 [ERROR] middleware.go:419: GET     | 500 | 192.168.2.10:61804 | "/api/resources?path=%2FMedia%2Fname.srt&source=srv&content=true"
2025/06/08 05:22:33 [DEBUG] raw.go:235: User admin is downloading large (695 MB) file: name.S01E06.1080p.mp4
2025/06/08 05:22:33 [INFO ] middleware.go:419: GET     | 304 | 192.168.2.10:61804 | "/api/raw?files=srv::%2FMedia%2Fname.S01E06.1080p.mp4&inline=true"
2025/06/08 05:22:33 [DEBUG] raw.go:235: User admin is downloading large (695 MB) file: name.S01E06.1080p.mp4
2025/06/08 05:22:33 [INFO ] middleware.go:419: GET     | 206 | 192.168.2.10:61804 | "/api/raw?files=srv::%2FMedia%2Fname.S01E06.1080p.mp4&inline=true"

**Comment by gtsteffaniak** [comment]
Ah great catch checking out the code, you're exactly right the filename with multiple "." Extension is likely the issue.

I will fix this. I usually avoid regex where possible because it's more cpu intensive and less coherent when skimming the code. This can easily be fixed by updating the check logic.

**Comment by 3zero2** [comment]
This still happens to me with version 0.7.9.

In the error message I can see that the path is missing a / right before the video file name. An example:

Video File Name: a.mp4
Location: /movies/kids/a.mp4

Filebrowser tries to open /movies/kidsa.srt rather than /movies/kids/a.srt

**Comment by gtsteffaniak** [comment]
I think this was fixed in 0.7.10, can you confirm?

**Comment by 3zero2** [comment]
Confirmed. Error message does not appear on 0.7.10
